#!/bin/sh
# /etc/uci-defaults/99-set-hostname

if grep -q 'nvme' /proc/partitions; then
    hostname="BPI-R4-NVMe"
elif grep -q 'mmcblk0boot0' /proc/partitions; then
    hostname="BPI-R4-eMMC"
elif grep -q 'mmcblk0' /proc/partitions; then
    hostname="BPI-R4-SD"
else
    hostname="BPI-R4"
fi

uci set system.@system[0].hostname="$hostname"
uci commit system
