#!/bin/sh
if [ -f /sys/firmware/devicetree/base/chosen/rootdisk-nvme ]; then
    hostname="BPI-R4-NVMe"
elif [ -f /sys/firmware/devicetree/base/chosen/rootdisk-emmc ]; then
    hostname="BPI-R4-eMMC"
elif [ -f /sys/firmware/devicetree/base/chosen/rootdisk-sd ]; then
    hostname="BPI-R4-SD"
elif [ -f /sys/firmware/devicetree/base/chosen/rootdisk-nand ]; then
    hostname="BPI-R4-NAND"
else
    hostname="BPI-R4"
fi
uci set system.@system[0].hostname="$hostname"
uci commit system
